feature/auto-launch-linepay-for-ios
enpitut2021/chimimoryo_autumn pull request #15
Opened 2021-12-01 05:49 UTC by takumah1234

- やったこと
アプリを起動すると自動でランダムなPayを起動するようにした．
ただし，店は常に"SevenEleven"にしている．
今後，この店のところはGPSか何かで取得した店になると思っている．

2021-12-01 22:32 UTC, ProfFunami requested changes

2021-12-01 22:32 UTC, ProfFunami commented on lib/main.dart
> +
`initState` で`launchRandomPay`を呼び出すと、端末起動時(アプリ初期起動時かもしれない)から店がセブンであると固定されてしまう

ホームウィジェットからアプリが開かれたかを認識して実行する関数は #14 で`void _launchedFromWidget`関数で実装されているので、`initState`関数とは別の関数を設けてその中で`launchRandomPay`を呼び出すようにしておいたほうが良さそう

2021-12-02 01:23 UTC, takumah1234 commented on lib/main.dart
> +
> initState でlaunchRandomPayを呼び出すと、端末起動時(アプリ初期起動時かもしれない)から店がセブンであると固定されてしまう

ここはまさにその通りだと思うけど，Ramdomで呼び出すのは処理として正しい？起動→場所を取得→その場所に基づいてlaunchするのかなと思って，一旦セブンで固定しているという判断なんだけど．

> ホームウィジェットからアプリが開かれたかを認識して実行する関数は #14 でvoid _launchedFromWidget関数で実装されているので、initState関数とは別の関数を設けてその中でlaunchRandomPayを呼び出すようにしておいたほうが良さそう

今回のPBIではウィジェットを使わない＋`_launchedFromWidget`関数内でlaunchRandomPayを使うのかなって思ったからこの処理にしているよ．

ただ，読んでいて確かに場所の取得とその結果に基づいた関数の発火は一連の流れとしてまとめておくと良さそうなので，そこは入れておきます．

2021-12-02 01:38 UTC, ProfFunami approved these changes

2021-12-02 06:07 UTC, yoshinobc commented
よさそう

2021-12-02 06:08 UTC, yoshinobc approved these changes

2021-12-02 06:14 UTC, merged