クーポン情報が書かれたCSVファイルからfirebase storeにデータを追加するためのpythonスクリプト
enpitut2021/chimimoryo_autumn pull request #19
Opened 2021-12-10 08:02 UTC by yoshinobc

## Motivation
- 手作業で作ったクーポン情報が書かれたCSVファイルを手作業でfirebase storeに入れるのは大変なので，自動化するためのスクリプト

## Description of the changes
- gitignoreファイルにfirebase秘密鍵の追加
- requirements.txtの追加
- insert_data.pyの追加
- CSVファイルの追加

## 注意
- currentディレクトリに別で共有したfirebaseの秘密鍵を設置しておいてください．
- `python_script/insert_data.py --path {importするCSVファイルのパス} --collection {データを設置するコレクション名}`で実行してください．
- `--path`でimportしたいcsvファイル，`--collection`でデータを設置するコレクション名を選択できます．

2021-12-10 08:17 UTC, yoshinobc commented
同じ場所のPayがまとめられないという問題を見つけたため，後程修正します．

2021-12-12 16:10 UTC, yoshinobc commented
直した

2021-12-15 07:23 UTC, sudame requested changes

2021-12-15 07:23 UTC, sudame commented on python_scripts/insert_data.py
> +    coupon_doc_ref = document.collection("Payes").document()
"Pays" では？

2021-12-15 11:36 UTC, yoshinobc commented on python_scripts/insert_data.py
> +    coupon_doc_ref = document.collection("Payes").document()
"Pays"ですね，修正します．

2021-12-17 06:25 UTC, sudame approved these changes

2021-12-17 06:26 UTC, takumah1234 approved these changes
LGTM

2021-12-17 06:54 UTC, merged