change: ボタンを押したらPayPayが起動するようになった（iOSアプリ限定）
enpitut2021/chimimoryo_autumn pull request #5
Opened 2021-11-12 07:41 UTC by takumah1234

before：ボタンを押したらLinePayが起動
after：ボタンを押したら**PayPay**が起動

なお、対象はiOSアプリのみ

スクリーンショットはセキュリティ上の問題のため掲載はなし

2021-11-12 07:43 UTC, sudame requested changes

2021-11-12 07:43 UTC, sudame commented on ios/Runner/Info.plist
> +	  <string>paypay</string>
なんかインデントがキモい

2021-11-12 07:43 UTC, sudame commented on lib/main.dart
> +            const url = "paypay://";
これだと Android で起動しないので
https://qiita.com/Tazake/items/b3061bf941a413c74fed
あたりを見て「iOSなら」みたいな処理を挟んでほしい

2021-11-12 07:47 UTC, takumah1234 commented on ios/Runner/Info.plist
> +	  <string>paypay</string>
91ca2f2b3560efe8f2208120b7c174b97be55ecc で対応しました
インデントの揃える方法（tab or space）が違ったのが原因でした。

2021-11-12 07:52 UTC, takumah1234 commented on lib/main.dart
> +            const url = "paypay://";
072f633 で対応しました。
AndroidならLinePayを起動するように変更

2021-11-12 08:10 UTC, sudame approved these changes
LGTM

2021-11-18 13:03 UTC, ProfFunami approved these changes
iOSでもできるようになってるみたいなので、prタイトルを変更した

2021-11-18 13:06 UTC, merged